services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://fantasy:football@db:5432/tracker

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fantasy
      POSTGRES_PASSWORD: football
      POSTGRES_DB: tracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
